services:
  researcher_agent:
    build: ./researcher_agent
    ports:
      - "8000:8000"
    volumes:
      - ./researcher_agent:/app
    environment:
      - EXA_API_KEY=${EXA_API_KEY}
      - WANDB_API_KEY=${WANDB_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 2

  orchestrator_agent:
    build: ./orchestrator_agent
    ports:
      - "8001:8000"
    volumes:
      - ./orchestrator_agent:/app
    depends_on:
      researcher_agent:
        condition: service_healthy
